# Generated by Django 2.1.7 on 2019-02-18 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='position',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
