# Generated by Django 2.1.7 on 2019-03-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0006_auto_20190226_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='partylist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
